# Generated by Django 3.0 on 2020-08-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='available',
        ),
    ]
